// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SummitSample.TodoService.Data.SqlServer.DataAccess.Entities;

public partial class User
{
    public int Id { get; set; }

    public string LastName { get; set; }

    public string FirstName { get; set; }

    public virtual ICollection<TodoItem> TodoItems { get; set; } = new List<TodoItem>();
}