// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace SummitSample.UserService.Data.SqlServer.DataAccess.Entities;

public partial class TodoItem
{
    public int Id { get; set; }

    public int UserId { get; set; }

    public string Text { get; set; } = null!;

    public bool IsCompleted { get; set; }

    public bool IsImportant { get; set; }

    public virtual User User { get; set; } = null!;
}